Update after merge and review + change Common
В текущей ситуации странно иметь Task DeleteAsync(TKey guid);, потому что мы почти никогда не знаем без обращения к таблице в сервисах, что удаляемая сущность существует. Только в очень специфических ситуациях. Например, если добавили, но потом зачем-то решили удалить.

Также обновил сам DeleteAsync, поскольку нашёл более удачный метод (SingleDeleteAsync). Аналогичный метод есть и для UpdateAsync, но он нам не подходит, потому что мы хотим возвращать модельку

Проверил в Postman и понял, что не работает
`public virtual async Task<TEntity> GetAsync(TKey guid)
{
    return await Context.FindAsync<TEntity>(guid);
}`

Сама ошибка:
System.AggregateException: One or more errors occurred. (The key value at position 0 of the call to 'DbSet<DbOffice>.Find' was of type 'Guid', which does not match the property type of 'int'.)
 ---> System.ArgumentException: The key value at position 0 of the call to 'DbSet<DbOffice>.Find' was of type 'Guid', which does not match the property type of 'int'.
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.FindTracked(Object[] keyValues, IReadOnlyList`1& keyProperties)
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.FindAsync(Object[] keyValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.FindAsync[TEntity](Object[] keyValues)
   at Common.Repositories.ReadOnlyRepository`2.GetAsync(TKey guid) in C:\Users\Pavel\Documents\GitHub\OfficeMap\OfficeMapApi\Common\Repositories\ReadOnlyRepository.cs:line 39
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at OfficeService.Services.OfficesService.DeleteAsync(Guid officeguid) in C:\Users\Pavel\Documents\GitHub\OfficeMap\OfficeMapApi\OfficeService\OfficeService\Services\OfficesService.cs:line 49
   at OfficeService.Controllers.OfficeController.DeleteOffice(Guid officeGuid) in C:\Users\Pavel\Documents\GitHub\OfficeMap\OfficeMapApi\OfficeService\OfficeService\Controllers\OfficeController.cs:line 61
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)